name: Update gitignore file
on:
  schedule:
    # daily at 00:00
    - cron: '0 0 * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  update-gitignore:
    uses: kitsuyui/gh-actions-workflows/.github/workflows/gitignore-in.yml@8019e658f4665c962d0a88eb38b3b6be418e7be8 # main
